services:
  
  dh:
    image: postgres:latest
    container_name: postgres
    ports:
      - 6032:6032
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=widget-server

  app: 
    build: .
    ports: 
      - 3000:3333
    environment:
      - CLOUDFLARE_ACCOUNT_ID=#
      - CLOUDFLARE_ACCESS_KEY_ID=#
      - CLOUDFLARE_SECRET_ACCESS_KEY=#
      - CLOUDFLARE_BUCKET=#
      - CLOUDFLARE_PUBLIC_URL=http://localhost